name: Example Workflow

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  example-job:
    name: Example Job
    environment: main_environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Hello world action step
        id: hello
        uses: CapybaraOrg/capybara-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Run example process
        run: |
          ./process.sh
