name: Example Workflow

on:
  schedule:
    - cron: '00 1 * * 1'  # At 01:00 on Mondays.
  workflow_dispatch:
    inputs:
      isCapybaraDispatch:
        description: System only property (ignore)
        required: true
        default: 'false'

defaults:
  run:
    shell: bash

jobs:
  example-job:
    name: Example Job
    environment: main_environment
    runs-on: ubuntu-latest
    steps:
      - name: Capybara action
        id: capybara
        uses: CapybaraOrg/capybara-action@v1.0.3
        with:
          github-token: ${{ github.token }}
          isCapybaraDispatch: ${{ inputs.isCapybaraDispatch }}
          capybaraUrl: ${{ secrets.CAPYBARA_URL }}
          clientId: ${{ secrets.CAPYBARA_CLIENT_ID }}
          workflowId: 'example-workflow.yml'
          repoName: 'capybara-demo'
          ref: ${{ github.ref_name }}
          owner: ${{ github.repository_owner }}
          durationInMinutes: '10'
          maximumDelayInSeconds: '10800'
          location: 'eastus'
      - name: Print Capybara action output
        run: echo "The greenest time to run your workflow is calculated - your run will start approximately at ${{ steps.capybara.outputs.bestTimeToStart }}"
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Run example process
        run: |
          ./process.sh
